name: max_notes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view:
  get:
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  flutter_quill: ^10.7.7
  flutter_bloc: ^8.1.0   # flutter_quill requires flutter_bloc for state management

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
